# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
commands:
  echo_string:
    parameters:
      to:
        type: string
        default: "default string  to print"
    steps:
       - run: echo << parameters.to >>
jobs:
  failuer_job:
    docker:
        - image:  circleci/node:13.8.0
    steps:
        - run: return 1
        - run:
            name: "On Error"
            command: echo "Erro happend"
            when: on_fail
            

  print_using_params:
    docker:
        - image: circleci/node:13.8.0
    steps: 
        - echo_string :
           to : "Hello Odai Atef this is paramater"
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
         name: "echo OWNER NAME ENV"
         command: |
              echo $OWNER
  
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
        - run:
            name: "Save my name to file"
            command: echo "Hello Odai Atef" > ~/out.txt
        - persist_to_workspace:
            root: ~/
            paths:
             - out.txt        

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
        - attach_workspace:
            at: ~/ 
        - run:
            name: "Read File"
            command:  cat ~/out.txt

        
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - failuer_job
      - print_using_params 
      - save_hello_world_output
      - print_output_file:
           requires:
               - "save_hello_world_output"
      # - print_hello
      # - print_world:
        #  requires:
          #  - print_hello